//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ReliMobileModel", "FK__messages__sendFr__1CF15040", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReliMobileAdmin.Models.user), "message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReliMobileAdmin.Models.message), true)]
[assembly: EdmRelationshipAttribute("ReliMobileModel", "FK__messages__sendTo__1DE57479", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReliMobileAdmin.Models.user), "message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReliMobileAdmin.Models.message), true)]
[assembly: EdmRelationshipAttribute("ReliMobileModel", "FK__messages__replyT__403A8C7D", "message", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReliMobileAdmin.Models.message), "message1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReliMobileAdmin.Models.message), true)]

#endregion

namespace ReliMobileAdmin.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReliMobileEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReliMobileEntities object using the connection string found in the 'ReliMobileEntities' section of the application configuration file.
        /// </summary>
        public ReliMobileEntities() : base("name=ReliMobileEntities", "ReliMobileEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReliMobileEntities object.
        /// </summary>
        public ReliMobileEntities(string connectionString) : base(connectionString, "ReliMobileEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReliMobileEntities object.
        /// </summary>
        public ReliMobileEntities(EntityConnection connection) : base(connection, "ReliMobileEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<message> messages
        {
            get
            {
                if ((_messages == null))
                {
                    _messages = base.CreateObjectSet<message>("messages");
                }
                return _messages;
            }
        }
        private ObjectSet<message> _messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<warning> warnings
        {
            get
            {
                if ((_warnings == null))
                {
                    _warnings = base.CreateObjectSet<warning>("warnings");
                }
                return _warnings;
            }
        }
        private ObjectSet<warning> _warnings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomessages(message message)
        {
            base.AddObject("messages", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the warnings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowarnings(warning warning)
        {
            base.AddObject("warnings", warning);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReliMobileModel", Name="message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new message object.
        /// </summary>
        /// <param name="messageId">Initial value of the messageId property.</param>
        /// <param name="messageContent">Initial value of the messageContent property.</param>
        /// <param name="createdAt">Initial value of the createdAt property.</param>
        /// <param name="sendFromUserId">Initial value of the sendFromUserId property.</param>
        /// <param name="sendToUserId">Initial value of the sendToUserId property.</param>
        /// <param name="isReceived">Initial value of the isReceived property.</param>
        public static message Createmessage(global::System.Int32 messageId, global::System.String messageContent, global::System.DateTime createdAt, global::System.Int32 sendFromUserId, global::System.Int32 sendToUserId, global::System.Boolean isReceived)
        {
            message message = new message();
            message.messageId = messageId;
            message.messageContent = messageContent;
            message.createdAt = createdAt;
            message.sendFromUserId = sendFromUserId;
            message.sendToUserId = sendToUserId;
            message.isReceived = isReceived;
            return message;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 messageId
        {
            get
            {
                return _messageId;
            }
            set
            {
                if (_messageId != value)
                {
                    OnmessageIdChanging(value);
                    ReportPropertyChanging("messageId");
                    _messageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("messageId");
                    OnmessageIdChanged();
                }
            }
        }
        private global::System.Int32 _messageId;
        partial void OnmessageIdChanging(global::System.Int32 value);
        partial void OnmessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String messageContent
        {
            get
            {
                return _messageContent;
            }
            set
            {
                OnmessageContentChanging(value);
                ReportPropertyChanging("messageContent");
                _messageContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("messageContent");
                OnmessageContentChanged();
            }
        }
        private global::System.String _messageContent;
        partial void OnmessageContentChanging(global::System.String value);
        partial void OnmessageContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageUrl
        {
            get
            {
                return _imageUrl;
            }
            set
            {
                OnimageUrlChanging(value);
                ReportPropertyChanging("imageUrl");
                _imageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageUrl");
                OnimageUrlChanged();
            }
        }
        private global::System.String _imageUrl;
        partial void OnimageUrlChanging(global::System.String value);
        partial void OnimageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdAt
        {
            get
            {
                return _createdAt;
            }
            set
            {
                OncreatedAtChanging(value);
                ReportPropertyChanging("createdAt");
                _createdAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdAt");
                OncreatedAtChanged();
            }
        }
        private global::System.DateTime _createdAt;
        partial void OncreatedAtChanging(global::System.DateTime value);
        partial void OncreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sendFromUserId
        {
            get
            {
                return _sendFromUserId;
            }
            set
            {
                OnsendFromUserIdChanging(value);
                ReportPropertyChanging("sendFromUserId");
                _sendFromUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sendFromUserId");
                OnsendFromUserIdChanged();
            }
        }
        private global::System.Int32 _sendFromUserId;
        partial void OnsendFromUserIdChanging(global::System.Int32 value);
        partial void OnsendFromUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sendToUserId
        {
            get
            {
                return _sendToUserId;
            }
            set
            {
                OnsendToUserIdChanging(value);
                ReportPropertyChanging("sendToUserId");
                _sendToUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sendToUserId");
                OnsendToUserIdChanged();
            }
        }
        private global::System.Int32 _sendToUserId;
        partial void OnsendToUserIdChanging(global::System.Int32 value);
        partial void OnsendToUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isReceived
        {
            get
            {
                return _isReceived;
            }
            set
            {
                OnisReceivedChanging(value);
                ReportPropertyChanging("isReceived");
                _isReceived = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isReceived");
                OnisReceivedChanged();
            }
        }
        private global::System.Boolean _isReceived;
        partial void OnisReceivedChanging(global::System.Boolean value);
        partial void OnisReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> replyToMessageId
        {
            get
            {
                return _replyToMessageId;
            }
            set
            {
                OnreplyToMessageIdChanging(value);
                ReportPropertyChanging("replyToMessageId");
                _replyToMessageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("replyToMessageId");
                OnreplyToMessageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _replyToMessageId;
        partial void OnreplyToMessageIdChanging(Nullable<global::System.Int32> value);
        partial void OnreplyToMessageIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReliMobileModel", "FK__messages__sendFr__1CF15040", "user")]
        public user sendFromUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendFr__1CF15040", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendFr__1CF15040", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> sendFromUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendFr__1CF15040", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("ReliMobileModel.FK__messages__sendFr__1CF15040", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReliMobileModel", "FK__messages__sendTo__1DE57479", "user")]
        public user sendToUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendTo__1DE57479", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendTo__1DE57479", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> sendToUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("ReliMobileModel.FK__messages__sendTo__1DE57479", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("ReliMobileModel.FK__messages__sendTo__1DE57479", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReliMobileModel", "FK__messages__replyT__403A8C7D", "message1")]
        public EntityCollection<message> repliedByMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<message>("ReliMobileModel.FK__messages__replyT__403A8C7D", "message1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<message>("ReliMobileModel.FK__messages__replyT__403A8C7D", "message1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReliMobileModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="姓名">Initial value of the 姓名 property.</param>
        public static user Createuser(global::System.Int32 userId, global::System.String email, global::System.String 姓名)
        {
            user user = new user();
            user.userId = userId;
            user.email = email;
            user.姓名 = 姓名;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 姓名
        {
            get
            {
                return _姓名;
            }
            set
            {
                On姓名Changing(value);
                ReportPropertyChanging("姓名");
                _姓名 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("姓名");
                On姓名Changed();
            }
        }
        private global::System.String _姓名;
        partial void On姓名Changing(global::System.String value);
        partial void On姓名Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> 所属公司
        {
            get
            {
                return _所属公司;
            }
            set
            {
                On所属公司Changing(value);
                ReportPropertyChanging("所属公司");
                _所属公司 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("所属公司");
                On所属公司Changed();
            }
        }
        private Nullable<global::System.Int32> _所属公司;
        partial void On所属公司Changing(Nullable<global::System.Int32> value);
        partial void On所属公司Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> 所属中心
        {
            get
            {
                return _所属中心;
            }
            set
            {
                On所属中心Changing(value);
                ReportPropertyChanging("所属中心");
                _所属中心 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("所属中心");
                On所属中心Changed();
            }
        }
        private Nullable<global::System.Int32> _所属中心;
        partial void On所属中心Changing(Nullable<global::System.Int32> value);
        partial void On所属中心Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> 是否为集团员工
        {
            get
            {
                return _是否为集团员工;
            }
            set
            {
                On是否为集团员工Changing(value);
                ReportPropertyChanging("是否为集团员工");
                _是否为集团员工 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("是否为集团员工");
                On是否为集团员工Changed();
            }
        }
        private Nullable<global::System.Boolean> _是否为集团员工;
        partial void On是否为集团员工Changing(Nullable<global::System.Boolean> value);
        partial void On是否为集团员工Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReliMobileModel", "FK__messages__sendFr__1CF15040", "message")]
        public EntityCollection<message> messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<message>("ReliMobileModel.FK__messages__sendFr__1CF15040", "message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<message>("ReliMobileModel.FK__messages__sendFr__1CF15040", "message", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReliMobileModel", Name="warning")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class warning : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new warning object.
        /// </summary>
        /// <param name="warningId">Initial value of the warningId property.</param>
        /// <param name="warningTitle">Initial value of the warningTitle property.</param>
        /// <param name="warningMessage">Initial value of the warningMessage property.</param>
        /// <param name="reportedAt">Initial value of the reportedAt property.</param>
        public static warning Createwarning(global::System.Int32 warningId, global::System.String warningTitle, global::System.String warningMessage, global::System.DateTime reportedAt)
        {
            warning warning = new warning();
            warning.warningId = warningId;
            warning.warningTitle = warningTitle;
            warning.warningMessage = warningMessage;
            warning.reportedAt = reportedAt;
            return warning;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 warningId
        {
            get
            {
                return _warningId;
            }
            set
            {
                if (_warningId != value)
                {
                    OnwarningIdChanging(value);
                    ReportPropertyChanging("warningId");
                    _warningId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("warningId");
                    OnwarningIdChanged();
                }
            }
        }
        private global::System.Int32 _warningId;
        partial void OnwarningIdChanging(global::System.Int32 value);
        partial void OnwarningIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String warningTitle
        {
            get
            {
                return _warningTitle;
            }
            set
            {
                OnwarningTitleChanging(value);
                ReportPropertyChanging("warningTitle");
                _warningTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("warningTitle");
                OnwarningTitleChanged();
            }
        }
        private global::System.String _warningTitle;
        partial void OnwarningTitleChanging(global::System.String value);
        partial void OnwarningTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String warningMessage
        {
            get
            {
                return _warningMessage;
            }
            set
            {
                OnwarningMessageChanging(value);
                ReportPropertyChanging("warningMessage");
                _warningMessage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("warningMessage");
                OnwarningMessageChanged();
            }
        }
        private global::System.String _warningMessage;
        partial void OnwarningMessageChanging(global::System.String value);
        partial void OnwarningMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime reportedAt
        {
            get
            {
                return _reportedAt;
            }
            set
            {
                OnreportedAtChanging(value);
                ReportPropertyChanging("reportedAt");
                _reportedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("reportedAt");
                OnreportedAtChanged();
            }
        }
        private global::System.DateTime _reportedAt;
        partial void OnreportedAtChanging(global::System.DateTime value);
        partial void OnreportedAtChanged();

        #endregion

    
    }

    #endregion

    
}
